### Create policy

POST http://localhost:3000/policy
Content-Type: application/json

{
    "emergencyCoverage": 20000,
    "plasticSurgery": 30000,
    "dentistCoverage": 40000,
    "duration": 3
}

### Get all policies

GET http://localhost:3000/policy?page=1&limit=4
