### Sign up client

POST http://localhost:3000/users/client
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "1234"
}

### Login client

POST http://localhost:3000/users/client/login
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "1234"
}

### Current user

GET http://localhost:3000/users/client


### Logout client

POST http://localhost:3000/users/client/logout

### Sign up insurer

POST http://localhost:3000/users/insurer
Content-Type: application/json

{
    "name": "ALDAGI4",
    "password": "1234"
}

### Login insurer

POST http://localhost:3000/users/insurer/login
Content-Type: application/json

{
    "name": "ALDAGI4",
    "password": "1234"
}

### Get insurer

GET http://localhost:3000/users/insurer
